version: "3.4"

services:
  #! the first service is the apache zookeeper to manage the kafka cluster
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    # External : Internal ports
    ports:
      - "2181:2181"
    volumes:
      # The dierctory on the host is `zookeeper_data`
      # `bitnami` is the mapped folder in the container
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
   
networks:
  default:
    external:
      name: post_service_network
